dependencies:
 - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
 solc:
  remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
dotenv: .env
wallets:
  from_key: ${TESTNET_PRIVATE_KEY}

networks:
  default: development
  goerli:
    verify: True
  mainnet-fork:
    verify: False
  mainnet-fork-dev:
    verify: False
  ganache-local:
    verify: False
  development:
    verify: False